INSERT INTO STAGE.STATUS (STATUS_CD, STATUS_DES) VALUES ('PEND ', 'PENDING');
INSERT INTO STAGE.STATUS (STATUS_CD, STATUS_DES) VALUES ('COMP ', 'COMPLETE');
INSERT INTO STAGE.STATUS (STATUS_CD, STATUS_DES) VALUES ('ERROR', 'ERROR');

COMMIT;